account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('signup/',views.sign_up,name='signup'),
]

blog/urls.py
from django.urls import path
from . import views

app_name='blog'
urlpatterns = [
    path('', views.blog,name='blog'),
    path('<int:num>/', views.post_details,name='post_detail'),
    path('author/<str:auth>/', views.blog,name='author'),
    path('category/<str:cat>/', views.blog,name='category'),
    path('search/', views.search,name='search'),
    path('test/', views.test,name='test'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('blog/',include('blog.urls')),
    path('captcha/', include('captcha.urls')),
    path('account/',include('account.urls')),
    path('summernote/', include('django_summernote.urls')),
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
    path('', views.index,name='index'),
    path('contact/', views.contact,name='contact'),
    path('about/', views.about,name='about'),
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    
    child='child'
    teen='teen'
    adult='adult'
    
    AGE_FIELDS=(
        (child,'child'),(teen,'teen'),(adult,'adult')
    )
    
    title=models.CharField(max_length=255)
    content=models.TextField()
    created_time=models.DateTimeField(auto_now_add=True)
    updated_time=models.DateTimeField(auto_now=True)
    Active=models.BooleanField(default=False)
    age=models.CharField(max_length=255,default=adult,choices=AGE_FIELDS)
    author=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    category=models.ManyToManyField("Category")
    image=models.ImageField(upload_to='blog/',null=True,default='blog/sport.jpg')
    
    def __str__(self):
        return self.title

    class Meta:
        ordering=['-updated_time']
        
class Description(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    subject=models.CharField(max_length=50,null=True)
    message=models.TextField(blank=True)
    
    def __str__(self):
        return self.subject
    
class Category(models.Model):
    name=models.CharField(max_length=255)
    
    def __str__(self):
        return self.name
    

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    email=models.EmailField()
    subject=models.CharField(max_length=255)
    message=models.TextField()
    created_time=models.DateTimeField(auto_now_add=True)
    Active=models.BooleanField(default=False)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering=['-created_time']
    
    
    
        
            

home/models.py
from django.db import models

class Contact(models.Model):
    name=models.CharField(max_length=50,verbose_name='full name')
    email=models.EmailField()
    subject=models.CharField(max_length=50)
    message=models.TextField()
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name='مخاطب'
        verbose_name_plural='مخاطبان'

    
    
    
    

blog/forms.py
from django import forms
from home.models import Contact
from .models import Comment

# class TestForm(forms.Form):
#     name=forms.CharField(max_length=180)
#     email=forms.EmailField()
#     subject=forms.CharField(max_length=250)
#     message=forms.CharField(widget=forms.Textarea)
    
class TestForm(forms.ModelForm):
    
    class Meta:
        model=Contact
        fields='__all__'
        
class CommentForm(forms.ModelForm):
    
    class Meta:
        model=Comment
        fields=['post','name','email','subject','message']
        
        
    

home/forms.py
from django import forms
from .models import Contact
from captcha.fields import CaptchaField

class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model=Contact
        fields='__all__'

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login ,logout,authenticate
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.decorators import login_required

def login_view(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username,password=password)
        if user:
            login(request,user)
            return redirect('/')
        
    
    return render(request,'account/login.html')

@login_required
def logout_view(request):
    logout(request)
    return redirect('/')


def sign_up(request):
    
    if not request.user.is_authenticated:
        if request.method=='POST':
            form=UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('/')
    form=UserCreationForm()
    return render(request,'account/signup.html',{'form':form})

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Post,Comment
from home.models import Contact
from django.http import HttpResponse
from .forms import TestForm,CommentForm
from django.contrib.auth.decorators import login_required

def blog(request,**kwargs):
    
    posts=Post.objects.filter(Active=1)
    if kwargs.get('auth'):
        posts=posts.filter(author__username=kwargs['auth'])
    elif kwargs.get('cat'):
        posts=posts.filter(category__name=kwargs.get('cat'))
    context={'posts':posts}
    return render(request, 'blog/blog.html',context)

@login_required
def post_details(request,num):
    
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    form=CommentForm()
    #post=Post.objects.get(pk=num)
    post=get_object_or_404(Post,id=num)
    comments=Comment.objects.filter(post=post,Active=1)
    return render(request, 'blog/post-details.html',{'post':post,'comments':comments,'form':form})

def search(request):
    if request.method=='GET':
        s=request.GET.get('q')
        posts=Post.objects.filter(Active=1)
        posts=posts.filter(content__contain=s)
        return render(request,'blog/blog.html',{'posts':posts})
    
def test(request):
    
    if request.method=='POST':
        # name=request.POST.get('name')
        # email=request.POST.get('email')
        # subject=request.POST.get('subject')
        # message=request.POST.get('message')
      
        # form=TestForm(request.POST)
        # if form.is_valid():
        #     name=form.cleaned_data['name']
        #     email=form.cleaned_data['email']
        #     subject=form.cleaned_data['subject']
        #     message=form.cleaned_data['message']
        #     c=Contact()
        #     c.name=name
        #     c.email=email
        #     c.subject=subject
        #     c.message=message
        #     c.save()
        form=TestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        
    
    form=TestForm()
    return render(request,'test.html',{'form':form})

    
    

home/views.py
from django.shortcuts import render,redirect
from .forms import ContactForm
from django.contrib import messages

def index(request):
    context={'title':'MY page'}
    return render(request, 'home/index.html',context)

def about(request):
    return render(request, 'home/about.html')

def contact(request):
    if request.method=='POST':
        form=ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'your message set successfully')
            return redirect('/contact/')
    form=ContactForm()     
    return render(request, 'home/contact.html',{'form':form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>Stand CSS Blog by TemplateMo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="index.html"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:index' %}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:about'%}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:blog' %}">Blog Entries</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:contact' %}">Contact</a>
              </li>
              {% if request.user.is_authenticated%}
              <li class="nav-item">
                <a class="nav-link" href="">{{request.user.username}}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:signup' %}">Sign-up</a>
              </li>
              {% endif%}
            </ul>
          </div>
        </div>
      </nav>
    </header>

    {% block body %}

    {% endblock %}

     
    <footer>
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <ul class="social-icons">
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Behance</a></li>
                <li><a href="#">Linkedin</a></li>
                <li><a href="#">Dribbble</a></li>
              </ul>
            </div>
            <div class="col-lg-12">
              <div class="copyright-text">
                <p>Copyright 2020 Stand Blog Co.
                      
                   | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
              </div>
            </div>
          </div>
        </div>
      </footer>
  
      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  
      <!-- Additional Scripts -->
      <script src="{% static 'assets/js/custom.js' %}"></script>
      <script src="{% static 'assets/js/owl.js' %}"></script>
      <script src="{% static 'assets/js/slick.js' %}"></script>
      <script src="{% static 'assets/js/isotope.js' %}"></script>
      <script src="{% static 'assets/js/accordions.js' %}"></script>
  
      <script language = "text/Javascript"> 
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t){                   //declaring the array outside of the
        if(! cleared[t.id]){                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value='';         // with more chance of typos
            t.style.color='#fff';
            }
        }
      </script>
  
    </body>
  </html>

templates/blog/blog-categories.html
<div class="col-lg-12">
    <div class="sidebar-item categories">
      <div class="sidebar-heading">
        <h2>Categories</h2>
      </div>
      <div class="content">
        <ul>
          {% for cat,count in Dict.items %}
          <li><a href="{% url 'blog:category' cat=cat%}">{{cat}}:{{count}}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

templates/blog/blog-recent.html
{% load humanize %}
<div class="col-lg-12">
    <div class="sidebar-item recent-posts">
      <div class="sidebar-heading">
        <h2>Recent Posts</h2>
      </div>
      <div class="content">
        <ul>
          {% for post in posts|slice:'0:3'%}
          <li><a href="{% url 'blog:post_detail' num=post.id %}">
            <h5>{{post.title}}</h5>
            <span>{{post.updated_time| naturaltime}}</span>
          </a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

templates/blog/blog-search.html
<div class="col-lg-12">
    <div class="sidebar-item search">
      <form id="search_form" name="gs" method="GET" action="{% url 'blog:search' %}">
        <input type="text" name="q" class="searchText" placeholder="type to search..." autocomplete="on">
      </form>
    </div>
  </div>

templates/blog/blog-tags.html
<div class="col-lg-12">
    <div class="sidebar-item tags">
      <div class="sidebar-heading">
        <h2>Tag Clouds</h2>
      </div>
      <div class="content">
        <ul>
          <li><a href="#">Lifestyle</a></li>
          <li><a href="#">Creative</a></li>
          <li><a href="#">HTML5</a></li>
          <li><a href="#">Inspiration</a></li>
          <li><a href="#">Motivation</a></li>
          <li><a href="#">PSD</a></li>
          <li><a href="#">Responsive</a></li>
        </ul>
      </div>
    </div>
  </div>

templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
    {% block body %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Recent Posts</h4>
                <h2>Our Recent Blog Entries</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

    <section class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-content">
              <div class="row">
                <div class="col-lg-8">
                  <span>Stand Blog HTML5 Template</span>
                  <h4>Creative HTML Template For Bloggers!</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download Now!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                {% for post in posts%}
                <div class="col-lg-6">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{post.image.url}}" alt="">
                    </div>
                    <div class="down-content">
                      <span>Lifestyle</span>
                      <a href="{% url 'blog:post_detail' num=post.id %}"><h4>{{post.title|upper}}</h4></a>
                      <ul class="post-info">
                        <li><a href="{% url 'blog:author' auth=post.author%}">{{post.author}}</a></li>
                        <li><a href="#">{{post.created_time|date:'M Y d'}}</a></li>
                        <li><a href="#">12 Comments</a></li>
                      </ul>
                      <p>{{post.content|truncatewords:15}}.</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="#">Best Templates</a>,</li>
                              <li><a href="#">TemplateMo</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor%}
                <div class="col-lg-12">
                  <ul class="page-numbers">
                    <li><a href="#">1</a></li>
                    <li class="active"><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
              {% include 'blog/blog-search.html'%}
              {% recent_posts %}
              {% categories %}
              {% include 'blog/blog-tags.html'%}
              {% hello 'ali' %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    
    {% endblock %}

templates/blog/post-details.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
    {% block body %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Post Details</h4>
                <h2>Single blog post</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

    <section class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-content">
              <div class="row">
                <div class="col-lg-8">
                  <span>Stand Blog HTML5 Template</span>
                  <h4>Creative HTML Template For Bloggers!</h4>
                </div>
                <div class="col-lg-4">
                  <div class="main-button">
                    <a rel="nofollow" href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download Now!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">
                  <div class="blog-post">
                    <div class="blog-thumb">
                      <img src="{{post.image.url}}" alt="">
                    </div>
                    <div class="down-content">
                      <span>Lifestyle</span>
                      <a href="post-details.html"><h4>{{post.title|safe}}</h4></a>
                      <ul class="post-info">
                        <li><a href="{% url 'blog:author' auth=post.author %}">{{post.author.get_full_name}}</a></li>
                        <li><a href="#">{{post.created_time|date:'D d M Y'}}</a></li>
                        <li><a href="#">10 Comments</a></li>
                        category
                        {% for category in post.category.all %}
                        <li><a href="{% url 'blog:category' cat=category%}">{{category.name}}</a></li>
                        {% endfor%}
                      </ul>
                      <p>
                        {{post.content}}
                      .</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="#">Best Templates</a>,</li>
                              <li><a href="#">TemplateMo</a></li>
                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item comments">
                    <div class="sidebar-heading">
                      <h2>{{comments|length}} Comments</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for comment in comments%}
                        <li>
                          <div class="author-thumb">
                            <img src="{% static 'assets/images/comment-author-01.jpg' %}" alt="">
                          </div>
                          <div class="right-content">
                            <h4>{{comment.name}}<span>{{comment.created_time|date:'M Y d'}}</span></h4>
                            <p>{{comment.message}}</p>
                          </div>
                        </li>
                        <br>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item submit-comment">
                    <div class="sidebar-heading">
                      <h2>Your comment</h2>
                    </div>
                    <div class="content">
                      <form id="comment" action="{% url 'blog:post_detail' num=post.id%}" method="post">
                        {% csrf_token %}
                        <div class="row">
                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <input name="name" type="text" id="name" placeholder="Your name" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <input name="post" type="hidden"  value={{post.id}}   id="name" placeholder="Your name" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <input name="email" type="text" id="email" placeholder="Your email" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-12 col-sm-12">
                            <fieldset>
                              <input name="subject" type="text" id="subject" placeholder="Subject">
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="message" rows="6" id="message" placeholder="Type your comment" required=""></textarea>
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-button">Submit</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="sidebar">
              <div class="row">
              {% include 'blog/blog-search.html'%}
              {% recent_posts%}
              {% categories %}
              {% include 'blog/blog-tags.html'%}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}
    

templates/home/contact.html
{% extends 'base.html' %}
{% load static %}
    {% block body %}

    

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>contact us</h4>
                <h2>let’s stay in touch!</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->


    <section class="contact-us">
      <div class="container">
        <div class="row">
        
          <div class="col-lg-12">
            <div class="down-contact">
              <div class="row">
                <div class="col-lg-8">
                  <div class="sidebar-item contact-form">
                    <div class="sidebar-heading">
                      <h2>Send us a message</h2>
                    </div>
                    <div class="content">
                      <form id="contact" action="{% url 'home:contact' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <input name="name" type="text" id="name" placeholder="Your name" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-6 col-sm-12">
                            <fieldset>
                              <input name="email" type="text" id="email" placeholder="Your email" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-12 col-sm-12">
                            <fieldset>
                              <input name="subject" type="text" id="subject" placeholder="Subject">
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="message" rows="6" id="message" placeholder="Your Message" required=""></textarea>
                            </fieldset>
                          </div>
                          <div>
                          {{form.captcha}}<h2>Fill the captcha form</h2>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-button">Send Message</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>

                {% include 'message.html' %}
                
                <div class="col-lg-4">
                  <div class="sidebar-item contact-information">
                    <div class="sidebar-heading">
                      <h2>contact information</h2>
                    </div>
                    <div class="content">
                      <ul>
                        <li>
                          <h5>090-484-8080</h5>
                          <span>PHONE NUMBER</span>
                        </li>
                        <li>
                          <h5>info@company.com</h5>
                          <span>EMAIL ADDRESS</span>
                        </li>
                        <li>
                          <h5>123 Aenean id posuere dui, 
                          	<br>Praesent laoreet 10660</h5>
                          <span>STREET ADDRESS</span>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <div class="col-lg-12">
            <div id="map">
              <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>
          
        </div>
      </div>
    </section>
    {% endblock %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form</title>
</head>
<body>
    <form action="{% url 'blog:test' %}" method="post">
        {% csrf_token %}
        {% comment %} <div>
            <label>Name</label>
            <input name="name" type="text">
        </div>
        
        <div>
            <label>Email</label>
            <input name="email" type="text">
        </div>

        <div>
            <label>subject</label>
            <input name="subject" type="text">
        </div>
        
        <div>
            <label>Message</label>
            <input name="message" type="text">
        </div> {% endcomment %}

        {{form.as_p}}

        <button type="submit">Send</button>

    </form>
</body>
</html>